$(function(){
    var $main=$('#main');
    var $context=$(''
    // <!-- 头部导航栏部分 -->
    +'<div class="top">'
        +'<ul class="list">'
            +'<li class="li1">'
                +'<a href="">文件(F)</a>'
                +'<ul>'
                    +'<li>新建(N)</li>'
                    +'<li>新窗口(W)</li>'
                    +'<li>打开(O)...</li>'
                    +'<li>保存(S)</li>'
                    +'<li>另存为(A)...</li>'
                    +'<li>页面设置(U)...</li>'
                    +'<li>打印(P)</li>'
                    +'<li>退出(X)</li>'
                +'</ul>'
            +'</li>'
            +'<li class="li1">'
                +'<a href="">编辑(E)</a>'
                +'<ul>'
                    +'<li>撤销(U) &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Ctrl+Z</li>'
                    +'<li>剪切(T) &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Ctrl+X</li>'
                    +'<li>复制(C) &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Ctrl+C</li>'
                    +'<li>粘贴(P) &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Ctrl+V</li>'
                    +'<li>删除(L) &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Del</li>'
                    +'<li>替换(R) &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Ctrl+H</li>'
                    +'<li>转向(G) &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Ctrl+G</li>'
                    +'<li>全选(A) &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp Ctrl+A</li>'
                    +'<li>时间/日期(D) &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp F5</li>'
                +'</ul>'
            +'</li>'
            +'<li class="li1">'
                +'<a href="">格式(O)</a>'
                +'<ul>'
                    +'<li>自动换行(W)</li>'
                    +'<li id="fontsize">字体(F)</li>'
                +'</ul>'
            +'</li>'
            +'<li class="li1">'
                +'<a href="">查看(V)</a>'
                +'<ul>'
                    +'<li>缩放(Z)</li>'
                    +'<li>状态栏(S)</li>'
                +'</ul>'
            +'</li>'
            +'<li class="li1">'
                +'<a href="">帮助(H)</a>'
                +'<ul>'
                    +'<li>查看帮助(H)</li>'
                    +'<li>发送反馈(F)</li>'
                    +'<li>关于记事本(A)</li>'
                +'</ul>'
            +'</li>'
        +'</ul>'
    +'<div>'
    +'<div class="text">'
        +'<textarea name="" id="text1" cols="130" rows="40" style="font-size: 17px;"></textarea>'
    +'</div>'
    );
    $main.append($context);
    var $fontsize=$('#fontsize');
    $fontsize.click(function(){
        $ziti.show();
    })
})